### ISSUE TITLE
Propper scope for template creation

### ISSUE THREAD

**Issue by vaubarth** [vaubarth/upersetter#4]
If a file is being created from a template the template gets the top level scope of the options.
This means that it is not possible to pass scope from a template for loop in the options to the file template:

**options.yaml:**
```
languages:
  orig: EN
  to:
    - lang: FR
      translator: Anna
    - lang: DE
      translator: Jörg
    - lang: DK
      translator: Susi
```
**structure.yaml:**
```
{% for language in languages.to %}to_{{language.lang}}:
      files:
        - translator.txt:
            template: translator.txt.tpl
{% endfor %}
```
Here the template transator.txt.tpl should have _language_ as its scope but gets all of the options, meaning we cannot determine which language this template represents.
